import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className="h-screen w-screen px-4 bg-gradient-to-b from-emerald-50 to-orange-200">
            <div className="h-24">
                <Navbar/>
            </div>
            <div className="h-[calc(100vh-6rem)]">
                {children}
            </div>
        </div>
        </body>
        </html>
    );
}
